# Generated by Django 4.2 on 2023-05-10 16:21

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('primer_nombre', models.CharField(default='Julian', max_length=100)),
                ('segundo_nombre', models.CharField(blank=True, default='David', max_length=100)),
                ('primer_apellido', models.CharField(default='Perdigon', max_length=100)),
                ('segundo_apellido', models.CharField(blank=True, default='Rojas', max_length=100)),
                ('tipo_documento', models.CharField(choices=[('cedula', 'Cedula'), ('pasaporte', 'Pasaporte'), ('otro', 'Otro')], default='Cedula', max_length=20)),
                ('numero_documento', models.CharField(default='1000593957', max_length=50)),
                ('fecha_expedicion', models.DateField(default=django.utils.timezone.now)),
                ('telefono_movil', models.CharField(default='3225123570', max_length=20)),
                ('nacionalidad', models.CharField(default='Colombia', max_length=100)),
                ('departamento_residencia', models.CharField(default='Bogota', max_length=100)),
                ('ciudad_residencia', models.CharField(default='Bogota', max_length=100)),
                ('direccion', models.CharField(default='Cra 3A #12-19', max_length=200)),
                ('correo_electronico', models.EmailField(default='julianperdigon@usantotomas.edu.co', max_length=50)),
                ('contrasena', models.CharField(default='Showtime435.', max_length=50)),
                ('genero', models.CharField(choices=[('hombre', 'Hombre'), ('mujer', 'Mujer')], default='Hombre', max_length=10)),
                ('codigo_referido', models.CharField(blank=True, max_length=20)),
                ('acepto_notificaciones', models.BooleanField(default=False)),
                ('acepto_terminos', models.BooleanField(default=False)),
                ('id_usuario', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
            ],
        ),
    ]
