# Generated by Django 4.2 on 2023-05-10 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='tipo_documento',
            field=models.CharField(default='Cedula', max_length=20),
        ),
    ]
