# Generated by Django 4.2 on 2023-05-10 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_alter_projects_tipo_documento'),
    ]

    operations = [
        migrations.CreateModel(
            name='Apuestas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apuesta1', models.CharField(default='Julian', max_length=100)),
                ('apuesta2', models.CharField(blank=True, default='David', max_length=100)),
            ],
        ),
    ]
