# Generated by Django 4.2 on 2023-05-10 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_apuestas'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Projects',
            new_name='Base',
        ),
    ]
