# Generated by Django 4.2 on 2023-05-10 17:23

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_rename_projects_base'),
    ]

    operations = [
        migrations.CreateModel(
            name='Base2',
            fields=[
                ('primer_nombre2', models.CharField(default='Julian', max_length=100)),
                ('segundo_nombre2', models.CharField(blank=True, default='David', max_length=100)),
                ('primer_apellido2', models.CharField(default='Perdigon', max_length=100)),
                ('segundo_apellido2', models.CharField(blank=True, default='Rojas', max_length=100)),
                ('tipo_documento2', models.CharField(default='Cedula', max_length=20)),
                ('numero_documento2', models.CharField(default='1000593957', max_length=50)),
                ('fecha_expedicion2', models.DateField(default=django.utils.timezone.now)),
                ('telefono_movil2', models.CharField(default='3225123570', max_length=20)),
                ('nacionalidad2', models.CharField(default='Colombia', max_length=100)),
                ('departamento_residencia2', models.CharField(default='Bogota', max_length=100)),
                ('ciudad_residencia2', models.CharField(default='Bogota', max_length=100)),
                ('direccion2', models.CharField(default='Cra 3A #12-19', max_length=200)),
                ('correo_electronico2', models.EmailField(default='julianperdigon@usantotomas.edu.co', max_length=50)),
                ('contrasena2', models.CharField(default='Showtime435.', max_length=50)),
                ('genero2', models.CharField(choices=[('hombre', 'Hombre'), ('mujer', 'Mujer')], default='Hombre', max_length=10)),
                ('codigo_referido2', models.CharField(blank=True, max_length=20)),
                ('acepto_notificaciones2', models.BooleanField(default=False)),
                ('acepto_terminos2', models.BooleanField(default=False)),
                ('id_usuario2', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
            ],
        ),
    ]
