# Generated by Django 4.2 on 2023-05-12 16:52

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_rename_base2_registro_delete_base_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id_administrator', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('username', models.EmailField(default='julianperdigon@usantotomas.edu.co', max_length=50)),
                ('contrasena', models.CharField(default='Showtime435.', max_length=50)),
                ('correo_electronico', models.EmailField(default='julianperdigon@usantotomas.edu.co', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Deporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='registro',
            name='banco',
            field=models.CharField(default='BBVA', max_length=100),
        ),
        migrations.AddField(
            model_name='registro',
            name='fecha_nacimiento',
            field=models.DateField(default='2002-03-22'),
        ),
        migrations.CreateModel(
            name='TarjetaCredito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cc_number', models.CharField(default='123456789123', max_length=50)),
                ('cc_name', models.CharField(default='Julian David Perdigon Rojas', max_length=50)),
                ('contrasena', models.DateField(default='2023-05-10')),
                ('cc_csc', models.CharField(default='123', max_length=3)),
                ('id_TC', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.registro')),
            ],
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id_usuario', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('primer_nombre', models.CharField(default='Julian', max_length=100)),
                ('segundo_nombre', models.CharField(blank=True, default='David', max_length=100)),
                ('primer_apellido', models.CharField(default='Perdigon', max_length=100)),
                ('segundo_apellido', models.CharField(blank=True, default='Rojas', max_length=100)),
                ('fecha_nacimiento', models.DateField(default='2002-03-22')),
                ('telefono_movil', models.CharField(default='3225123570', max_length=20)),
                ('nacionalidad', models.CharField(default='Colombia', max_length=100)),
                ('ciudad_residencia', models.CharField(default='Bogota', max_length=100)),
                ('direccion', models.CharField(default='Cra 3A #12-19', max_length=200)),
                ('correo_electronico', models.EmailField(default='julianperdigon@usantotomas.edu.co', max_length=50)),
                ('genero', models.CharField(default='Hombre', max_length=10)),
                ('num_cuenta', models.CharField(default='53206', max_length=5)),
                ('banco', models.IntegerField(default=123456789)),
                ('id_ini', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.tarjetacredito')),
                ('id_perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.registro')),
            ],
        ),
        migrations.CreateModel(
            name='Liga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('deporte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.deporte')),
            ],
        ),
        migrations.CreateModel(
            name='IniciarSesion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.EmailField(default='julianperdigon@usantotomas.edu.co', max_length=50)),
                ('contrasena', models.CharField(default='Showtime435.', max_length=50)),
                ('id_ini', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.registro')),
            ],
        ),
        migrations.CreateModel(
            name='Eventos',
            fields=[
                ('id_evento', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('nombre_evento', models.CharField(max_length=255)),
                ('fecha_evento', models.DateField()),
                ('hora_evento', models.TimeField()),
                ('opcion_1', models.CharField(max_length=255)),
                ('opcion_1_prob', models.FloatField()),
                ('opcion_2', models.CharField(max_length=255)),
                ('opcion_2_prob', models.FloatField()),
                ('opcion_3', models.CharField(max_length=255)),
                ('opcion_3_prob', models.FloatField()),
                ('ganadora', models.CharField(default=None, max_length=255, null=True)),
                ('descripcion', models.TextField(default=None, null=True)),
                ('administrador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.admin')),
            ],
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('descripcion', models.TextField()),
                ('deporte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.deporte')),
                ('liga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.liga')),
            ],
        ),
        migrations.CreateModel(
            name='Apuesta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opcion_apuesta', models.CharField(choices=[('opcion_1', 'Opción 1'), ('opcion_2', 'Opción 2'), ('opcion_3', 'Opción 3')], max_length=50)),
                ('monto_apuesta', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_apuesta', models.DateTimeField(auto_now_add=True)),
                ('resultado_apuesta', models.CharField(blank=True, max_length=50, null=True)),
                ('ganancia', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('evento_apuesta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.eventos')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.perfil')),
            ],
        ),
    ]
