# Generated by Django 4.2 on 2023-06-09 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_admin_deporte_registro_banco_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='num_cuenta',
            field=models.CharField(default='75042', max_length=5),
        ),
    ]
